# Generated by Django 3.2.9 on 2021-11-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_cliente_pedidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='ariculo',
            new_name='articulo',
        ),
    ]
